### ISSUE TITLE
[1.14.4] Server crash at start

### ISSUE THREAD

**Issue by H4Mm3r** [strikerrocker/VanillaTweaks#113]
[12:04:52] [modloading-worker-5/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: vanillatweaks, class io.github.strikerrocker.vt.VanillaTweaks
java.lang.TypeNotPresentException: Type net.minecraftforge.common.loot.GlobalLootModifierSerializer not present
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) ~[?:1.8.0_212] {}
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) ~[?:1.8.0_212] {}
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_212] {}
        at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) ~[?:1.8.0_212] {}
        at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) ~[?:1.8.0_212] {}
        at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) ~[?:1.8.0_212] {}
        at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:94) ~[?:1.8.0_212] {}
        at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:283) ~[?:1.8.0_212] {}
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:283) ~[?:1.8.0_212] {}
        at net.minecraftforge.eventbus.ASMEventHandler.<init>(ASMEventHandler.java:58) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.register(EventBus.java:219) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:138) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:72) ~[eventbus-1.0.0-service.jar:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_212] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212] {}
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_212] {}
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_212] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_212] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_212] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_212] {}
        at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:72) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.eventbus.EventBus.register(EventBus.java:112) ~[eventbus-1.0.0-service.jar:?] {}
        at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$3(AutomaticEventSubscriber.java:70) ~[?:?] {re:classloading}
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212] {}
        at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:57) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:141) ~[?:28.2] {re:classloading}
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_212] {}
        at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_212] {}
        at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:134) ~[?:?] {re:classloading}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_212] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_212] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_212] {}
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_212] {}
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_212] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_212] {}
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.loot.GlobalLootModifierSerializer
        at java.lang.ClassLoader.findClass(ClassLoader.java:530) ~[?:1.8.0_212] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:103) ~[modlauncher-4.1.0.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212] {}
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212] {}
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212] {}
        at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[?:1.8.0_212] {}
        ... 41 more

[12:05:15] [Server thread/FATAL] [ne.mi.fm.ModLoader/LOADING]: Failed to complete lifecycle event CONSTRUCT, 1 errors found
[12:05:15] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        VanillaTweaks (vanillatweaks) has failed to load correctly
§7Type net.minecraftforge.common.loot.GlobalLootModifierSerializer not present
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}
[12:05:15] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /opt/minecraft_server_beta/./crash-reports/crash-2020-04-18_12.05.15-server.txt
[12:05:15] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[12:05:15] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[12:05:15] [Server thread/ERROR] [minecraft/MinecraftServer]: Exception stopping the server
java.lang.RuntimeException: The server has failed to initialize correctly due to mod loading errors. Examine the crash report for more details.
        at net.minecraftforge.common.DimensionManager.getWorld(DimensionManager.java:182) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.func_71218_a(MinecraftServer.java:979) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:521) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71260_j(DedicatedServer.java:544) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:661) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}

 - Forge Version: 28.2.3
 - MC Version: 1.14.4
 - Mod Version: 1.5.13
-  Curios Version (if present) : 1.0.6.1

The server won't start.

**Comment by strikerrocker** [comment]
Use the latest forge version 28.2.4. I will update the version for the game to even start.

**Comment by H4Mm3r** [comment]
It's working, and the two previous fixes are ok, thanks a lot !!
