### ISSUE TITLE
Game Crash after Selfplant of Mangrove-Propagule-Sapling

### ISSUE THREAD

**Issue by window-png** [strikerrocker/VanillaTweaks#176]
After a Mangrove drops a sapling by itself, the game crashes. Also player dropped sapling result in a crash.

After testing in the 1.19 version of Minecraft running fabric (ver. 0.14.8) the problem occurs both in single player and in multiplayer.

After a Mangrove drops a sapling by itself, the game crashes. During testing, also player dropped sapling result in a crash.

The game shows the following exit code:
`A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at net.minecraft.class_7115.method_41435(class_7115.java:146)
	at net.minecraft.class_7115.method_9558(class_7115.java:85)
	at net.minecraft.class_1542.handler$zjh000$tick(class_1542.java:589)
	at net.minecraft.class_1542.method_5773(class_1542.java:105)
	at net.minecraft.class_638.method_18646(class_638.java:267)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)

-- Entity being ticked --
Details:
	Entity Type: minecraft:item (net.minecraft.class_1542)
	Entity ID: 2322
	**_Entity Name: Mangrove Propagule_**
	Entity's Exact location: 4085.10, 63.00, 5363.76
	Entity's Block location: World: (4085,63,5363), Section: (at 5,15,3 in 255,3,335; chunk contains blocks 4080,-64,5360 to 4095,319,5375), Region: (7,10; contains chunks 224,320 to 255,351, blocks 3584,-64,5120 to 4095,319,5631)
	Entity's Momentum: 0.00, -0.12, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_638.method_32124(class_638.java:250)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:246)
	at net.minecraft.class_310.method_1574(class_310.java:1813)
	at net.minecraft.class_310.method_1523(class_310.java:1101)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['Titus_der_5te'/319, l='ClientLevel', x=4087.67, y=65.06, z=5370.97]]
	Chunk stats: 961, 820
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,69,0), Section: (at 0,5,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1270 game time, 1270 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods`

**Comment by purejosh** [comment]
@strikerrocker Please address this. This is causing crashes of both the server and client.

**Comment by jarocajavi** [comment]
I join the request, i have the same issue, in my case when a player join into some chunks with a Mangrove Propangule Sapling the server crash.

For now i fix this changing to "false" in "vanillatweaks.toml" the line "selfPlanting = true"

**Comment by strikerrocker** [comment]
For now I have disabled self planting working mangrove propagule in fabric version. The forge version still works. Will release an update today.

**Comment by jarocajavi** [comment]
This should be keep open, until you can fix it, right?

**Comment by purejosh** [comment]
Just remove the mod. Even with auto planting off, I was getting crashes from the mangrove propagule. Removed the mod, no more crashes.

**Comment by jarocajavi** [comment]
> Just remove the mod. Even with auto planting off, I was getting crashes from the mangrove propagule. Removed the mod, no more crashes.

You must to change the client config too, i had the same issue until edit the config client of all players
A good way to do it is using curseforge app for export a profile with selfplanting is in false.
