### ISSUE TITLE
[Bug] Crashing server when using enableFriedEgg = false

### ISSUE THREAD

**Issue by purejosh** [strikerrocker/VanillaTweaks#177]
When setting enableFriedEgg to false, it crashes the server. Here's the output: 

```[18:20:58] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalStateException: Some intrusive holders were not added to registry: [Reference{null=air}]
	at net.minecraft.class_2370.method_40276(class_2370.java:352) ~[server-intermediary.jar:?]
	at net.minecraft.class_2378.method_40292(class_2378.java:404) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cba001$beforeSetupServer(MinecraftServer.java:9292) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[18:20:58] [Server thread/ERROR]: This crash report has been saved to: C:\Users\minecraft\Desktop\Crafty Controller\servers\35a4febf-88a3-450f-9376-80914c3c033a\.\crash-reports\crash-2022-09-06_18.20.58-server.txt
[18:20:58] [Server thread/INFO]: Starting shutdown process...
[18:20:58] [Server thread/INFO]: Closing storage...
[18:20:58] [Server thread/INFO]: Goodbye!
[18:20:58] [Server thread/INFO]: Stopping server
[18:20:58] [Server thread/INFO]: Saving worlds
[18:20:58] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "$$5" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:531) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:592) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:547) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by strikerrocker** [comment]
I can't reproduce the issue by disabling fried egg. Can you provide the mod version, minecraft version and modloader? (Sorry for the late reply)

**Comment by purejosh** [comment]
VanillaTweaks-fabric-1.19-1.5.61
Fabric 1.19.2 server. 0.14.9 loader.

**Comment by strikerrocker** [comment]
Found the issue which is causing and investigating on how to fix it. This also seems to affect Storage blocks disabling too.

**Comment by purejosh** [comment]
Thank you.
