### ISSUE TITLE
Dedicated Server Crash

### ISSUE THREAD

**Issue by kreezxil** [strikerrocker/VanillaTweaks#27]
I got hung server and at the top of the errors that were being spit out was this:
```
[00:25:24] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockStateContainer{block=minecraft:double_stone_slab, properties=[seamless, variant]}
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockSlab$EnumBlockHalf, values=[top, bottom]} as it does not exist in BlockStateContainer{block=minecraft:double_stone_slab, properties=[seamless, variant]}
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201) ~[awu$a.class:?]
        at io.github.strikerrocker.vt.handlers.events.PlayerEvents.onRightClick(PlayerEvents.java:158) ~[PlayerEvents.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_506_PlayerEvents_onRightClick_RightClickBlock.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:1110) ~[ForgeHooks.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:433) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more
```

mods in my pack that I am building are:
https://gist.github.com/cb3923c4ff0c0ef6437d909e91c11c72

**Comment by strikerrocker** [comment]
@kreezxil For temporary solving the issue i would recommend currently disabling the `Sit on stairs` config option in Misc category.
