### ISSUE TITLE
New version broke Hops! 

### ISSUE THREAD

**Issue by Undesolate** [strikerrocker/VanillaTweaks#33]
**Vanilla Tweaks Version**:  1.2.10

 

**MinecraftForge Version**:  14.23.2.2654

 

**Minecraft Version**: 1.12

 

**(Optional) Just Enough Items (JEI) Version**:

 

**Client or Server?**:
- [ X] Client
- [ X] Server

**Crash Report (via. [Pastebin](http://pastebin.com/))**:

 

**What happens / happened?**:  Hops III does not work anymore on my enchanted boots

 

**How can I reproduce it?**:

 

**(Optional) Mod List**:

**Comment by strikerrocker** [comment]
Hmm thanks for reporting it should be an easy fix but i have real life work but i will release a fix as soon as possible. Thanks for reporting

**Comment by strikerrocker** [comment]
Looking at this new version broke all version

**Comment by strikerrocker** [comment]
Pushed an new build to curse. Now to wait for approving. Can you make sure this works @Undesolate

**Comment by Undesolate** [comment]
Hey Strikerrocker - I'm logging in now using the build you created yesterday (4-15-18) not the one you uploaded today (4-16-18). When I tried to run the one you uploaded today I got this error and the game crashed via client side. Hops does seem to work though! I'll let you know if I encounter anymore errors.


Caused by: java.lang.NullPointerException
	at io.github.strikerrocker.vt.capabilities.SelfPlantingProvider.<init>(SelfPlantingProvider.java:12)
	at io.github.strikerrocker.vt.events.VTEventHandler.addItemCaps(VTEventHandler.java:112)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_142_VTEventHandler_addItemCaps_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:657)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:627)
	at net.minecraft.entity.Entity.<init>(Entity.java:219)
	at net.minecraft.entity.item.EntityItem.<init>(EntityItem.java:73)
	at cpw.mods.ironchest.client.renderer.chest.TileEntityIronChestRenderer.<clinit>(TileEntityIronChestRenderer.java:43)

**Comment by strikerrocker** [comment]
The new build fixed it. It was due to some refractor i was doing in the build before that.

**Comment by Undesolate** [comment]
I guess I'm confused.. This is what I see on twitch 
![image](https://user-images.githubusercontent.com/38389195/38828154-fd85c572-4169-11e8-939f-4ad743b6dc78.png) 

This one dated 4-16-18 is the one that errors out. The one I currently have installed works perfectly.
