### ISSUE TITLE
Crash on Startup (1.15.2)

### ISSUE THREAD

**Issue by Supercarlover1** [strikerrocker/VanillaTweaks#93]
When I try to start minecraft, I keep getting an error:
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 3/16/20 8:23 PM
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for vanillatweaks:entity_sit
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[1.15.2-forge-31.1.23.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_74] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_74] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_74] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_74] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.23.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Mac OS X (x86_64) version 10.15.3
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6221921344 bytes (5933 MB) / 7952400384 bytes (7584 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 4
	JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.23.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.15.2_HD_U_G1_pre9_MOD.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.23.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.23
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.23-client.jar Minecraft {minecraft@1.15.2 COMMON_SETUP}
		lostcities-1.15-3.0.0-alpha.jar LostCities {lostcities@1.15-3.0.0-alpha COMMON_SETUP}
		VanillaTweaks-1.15.2.1.5.17.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.17 COMMON_SETUP}
		Cucumber-1.15.2-3.0.2.jar Cucumber Library {cucumber@3.0.2 COMMON_SETUP}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c COMMON_SETUP}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 COMMON_SETUP}
		AdvancedSkinCustomization-2.8.2.jar Advanced Skin Customization {advskinmod@2.8.2 COMMON_SETUP}
		travellersboots-1.15.2-1.3.2.jar Traveller's Boots {travellersboots@1.3.1 COMMON_SETUP}
		janoeo-3.2.jar Just Another Nether/Overworld/End Ores {janoeo@3.2 COMMON_SETUP}
		longfallboots-1.4.0b.jar Long Fall Boots {longfallboots@1.4.0b COMMON_SETUP}
		buzzierbees-1.2.jar Buzzier Bees {buzzierbees@1.2 COMMON_SETUP}
		CloudBoots-1.15.2-2.0.0.jar Cloud Boots Mod {cloudboots@2.0.0 COMMON_SETUP}
		forge-1.15.2-31.1.23-universal.jar Forge {forge@31.1.23 COMMON_SETUP}
		Aquaculture-1.15.2-2.0.11.jar Aquaculture 2 {aquaculture@1.15.2-2.0.11 COMMON_SETUP}
		MysticalAgradditions-1.15.2-3.0.0.jar Mystical Agradditions {mysticalagradditions@3.0.0 COMMON_SETUP}
		MiscAdditions-1.2.2.jar Misc Additions {miscadditions@1.2.2 COMMON_SETUP}
		goprone-1.15.x-1.1.1.jar GoProne {goprone@1.15.x-1.1.1 COMMON_SETUP}
		Waystones_1.15.2-6.0.0.jar Waystones {waystones@6.0.0 COMMON_SETUP}
		ForgeEndertech-1.15.2-6.0.0.0-build.0004.jar Forge Endertech {forgeendertech@6.0.0.0 COMMON_SETUP}
		AdHooks-1.15.2-5.0.0.0-build.0004.jar Advanced Hook Launchers {adhooks@5.0.0.0 COMMON_SETUP}
		gravestone-1.17.3.jar Gravestone Mod {gravestone@1.17.3 COMMON_SETUP}
		MysticalAgriculture-1.15.2-3.0.0.jar Mystical Agriculture {mysticalagriculture@3.0.0 COMMON_SETUP}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 COMMON_SETUP}
		BetterSprinting-1.15.2-v3.1.0.jar Better Sprinting {bettersprinting@3.1.0 COMMON_SETUP}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 COMMON_SETUP}
	Launched Version: 1.15.2-forge-31.1.23
	Backend library: LWJGL version 3.2.1 build 12
	Backend API: Intel(R) Iris(TM) Graphics 6100 GL version 2.1 INTEL-14.4.23, Intel Inc.
	GL Caps: Using framebuffer using ARB_framebuffer_object extension
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre9
	OptiFine Build: 20200223-095745
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-14.4.23
	OpenGlRenderer: Intel(R) Iris(TM) Graphics 6100
	OpenGlVendor: Intel Inc.
	CpuCount: 4

I've tried more than one version of the mod for 1.15.2

**Comment by Supercarlover1** [comment]
Never mind.  It was just Optifine causing problems.
